spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "123456"

  flyway:
    baseline-on-migrate: true

logging:
  config: classpath:logback-spring.xml
  logging.path: D:/log
