spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.56:3306/test
    username: root
    password: "123456"
  flyway:
    baseline-on-migrate: true

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      force-response: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:logback-spring.xml
